{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crm-web.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crm-web.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secrets | nindent 2 }}
{{- end }}
